---
  title: "Proje Rapor : Meryem Demirel 210401076"
output:
  html_document:
  df_print: paged
---
  
# Q1 : Problem tanımı
  
  Şirketimiz **bir inşaat şirketidir**. Problemimiz *Kaliforniya eyaletinde ki yaşı büyük oda sayısı az evlerini bulmaktır*.Şu anda üzerinde çalıştığımız ana sorun, Kaliforniya eyaletindeki konut projelerinde karşılaştığımız belirli bir durumu çözmektir. Problemimiz, yaşları daha büyük olan ve genellikle daha küçük odalara sahip olan evleri tespit etmektir. Bu tür evlerin belirlenmesi, konut projelerimizde stratejik planlama ve kaynak yönetimi konularında önemli bir rol oynamaktadır.
  
# Q2 : Proje Amacı 
[California House Price](https://www.kaggle.com/datasets/shibumohapatra/house-price/data) adli Kaggle veri setini kullanarak iş problemini  **data analizing** yöntemini kullanarak çözmeyi amaçlıyoruz. Bu sayede eski ve dar evleri bulup onları yeniden inşa edebileceğiz. Bunun yanında eski ama geniş evleri de bir iç mimarlık hizmeti vererek restore etmeyi amaçlıyoruz. Gelen müşterinin istekleri doğrultusunda da (uygun ev fiyatı oda sayısı gibi) onlara bir emlak hizmeti sunmayı hedefliyoruz.
